name: Super-Linter #nama dari CI

on: push #dijalankan ketika ada push ke repo

jobs: #Apa yg mau di kerjakan oleh CI
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
      
    env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}